FILEPATH_NAV = "data/mf_nav.csv"
FILEPATH_TRANSACTION = "data/transaction.csv"
FILEPATH_FUNDS = "data/funds.csv"
FILEPATH_CLOSING = "data/closing.csv"


FUND_HOUSE_MAPPING =  {            
    'icici': "ICICI",
    'mirae' :  'MIRAE ASSET',
    'hdfc' : 'HDFC',
    'axis': 'AXIS',
    'sbi': 'SBI',
    'nippon': 'NIPPON',
    'edelweiss': 'Edelweiss', 
    'dsp': 'DSP',
    'bnp': 'BNP','franklin': 'Franklin Templeton',
    'bharat' : 'Edelweiss',
    'kotak': 'Kotak Mahindra', 'kotka': 'Kotak Mahindra',
    'franklin': 'Franklin Templeton',
    'motilal': 'Motilal Oswal',
    'aditya': 'Aditya Birla',
    'iti': 'ITI',
    'baroda': 'Baroda',
    'mahindra': 'Mahindra',
    'parag': 'Parag Parikh',
    'principal': 'Principal',
    'quant': 'Quant',
    'indiabulls': 'India Bulls',
    'iifl': 'IIFL',
    'union' : 'Union',
    'uti': 'UTI',
    'pgim': 'PGIM India',
    'idbi': 'IDBI',
    'l&t': 'L&T',
    'essel': 'Essel',
    'idfc': 'IDFC', 'idfc-money': 'IDFC',
    'boi': 'BOI AXA',
    'boiaxaequity': 'BOI AXA', 'axa': 'BOI AXA',
    'invesco': 'Invesco',
    'quantum': 'Quantum',
    'hsbc': 'HSBC',
    'sundaram': 'SUNDARAM',
    'canara': 'Canara Robeco',
    'tata': 'TATA',
    'taurus': 'Taurus',
    'lic': 'LIC',
    'cpse': 'CPSE',
}